---
- name: create databases
  mysql_db:
    name: '{{ item.dbname }}'
    collation: '{{ item.collation }}'
    encoding: '{{ item.encoding }}'
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ db_socket }}"
  with_items: '{{ mariadb_databases }}'