---
- name: Ansible mysql Python modules dependancies are present.
  zypper:
    name: python3-PyMySQL
    state: present

- name: Mariadb Client packages are present.
  zypper: 
    name: mariadb-client
    state: present

- name: Mariadb server packages are present.
  zypper:
    name: mariadb
    state: present

- name: Configure Mariadb socket
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  register: mariadb_network

- name: re-start maridb service
  service:
    name: mariadb
    state: restarted
  when: mariadb_server_install.changed == true or mariadb_network.changed == true

- name: mariadb service is enabled
  service:
    name: mariadb
    state: started
    enabled: yes