---
- name: import centos7 install tasks
  import_tasks: install-centos.yml
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7") or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version == "8")

- name: import Ubuntu install tasks
  import_tasks: install-ubuntu.yml
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04") or
        (ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04") or
        (ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04")

- name: import Suse install tasks
  import_tasks: install-suse.yml
  when: ansible_os_family == "Suse"

- name: mysql_secure_installation
  import_tasks: mysql_secure_installation.yml

- name: mariadb databases
  import_tasks: databases.yml
  when: mariadb_databases is defined

- name: mariadb users
  import_tasks: users.yml
  when: mariadb_users is defined