---
- name: Root password present
  block:
    - name: 1. Root password is present and known
      mysql_user:
        login_user: root
        login_unix_socket: /var/lib/mysql/mysql.sock
        login_password: '{{ mariadb_root_password }}'
        name: root
      no_log: true  
  rescue:
    - name: 1. Root password is present
      mysql_user:
        login_user: root
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: root
        password: '{{ mariadb_root_password }}'
        host: localhost 
        state: present
      no_log: true
      register: root_password_present
- name: 2. Anonamous users absent
  mysql_user:
    login_user: root
    login_password: '{{ mariadb_root_password }}'
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: ''
    host_all: true
    state: absent
  no_log: true
- name: 3. Dissalow root login remote
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: root
    password: "{{ mariadb_root_password }}"
    host: '{{ item }}'
    state: present
  with_items:
    - ::1
    - 127.0.0.1
    - localhost
  no_log: true
- name: 4. Test database absent
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: test
    state: absent