---
- name: add static route to route-table with -ip route add- cmd
  command:
    cmd: "/usr/sbin/ip route add {{ item.destination }} via {{ item.gateway }} dev {{ item.device }}"
  register: iprouteadd_result
  failed_when: "'Cannot find device' in iprouteadd_result.stderr or 'Network is unreachable' in iprouteadd_result.stderr"
  changed_when: iprouteadd_result.rc == 0
  loop: "{{ statroute_list }}"

- name: Adding a static route to device static-route file, if not exists
  lineinfile:
    path: /etc/sysconfig/network-scripts/route-{{ item.device }}
    line: '{{ item.destination }} via {{ item.gateway }} dev {{ item.device }}'
    create: yes
    owner: root
    group: root
    mode: '0644'
    state: present
  loop: "{{ statroute_list }}"
